Add ability to place and remove block debug markers for players
pl3xgaming/Purpur pull request #1072
Opened 2022-07-23 14:00 UTC by YouHaveTrouble

Debug markers exist so we can visualize the locations in minecraft world. Plugins could use it to debug issues with block locations, help with labeling blocks with normally hidden data (maybe blocks that have added interaction from a plugin, etc).

This *can* be also used to mark a block for player, but it's not recomended as the display is not consistant on all client versions, for example current 1.19 version ignores highlight color unless fixed with a datapack or mod. This fact is pointed out in javadoc.

2022-07-23 20:14 UTC, BillyGalbreath commented on patches/server/0292-debug-marker-api.patch
> ++        packet.writeInt(new java.awt.Color(color.getRed(), color.getGreen(), color.getBlue(), transparency).getRGB());
```suggestion
+        packet.writeInt((transparency << 24) | (color.asRGB() & 0xFFFFFF));
```

2022-07-23 20:15 UTC, BillyGalbreath commented on patches/server/0292-debug-marker-api.patch
> ++        packet.writeInt(new java.awt.Color(color.getRed(), color.getGreen(), color.getBlue(), transparency).getRGB());
I would actually prefer to handle color as an int rather than a Bukkit or AWT Color so we're not forcing plugins to allocate an entire Object just for a color.

2022-07-25 18:21 UTC, YouHaveTrouble commented on patches/server/0292-debug-marker-api.patch
> ++        packet.writeInt(new java.awt.Color(color.getRed(), color.getGreen(), color.getBlue(), transparency).getRGB());
I left one method that uses bukkit Color in constructor to give a little tease and motivation to learn color ints to use the rest of the methods ;P

2022-07-27 09:53 UTC, BillyGalbreath requested changes

2022-07-27 09:53 UTC, BillyGalbreath commented on patches/api/0050-debug-marker-api.patch
> ++    public void sendBlockHighlight(@NotNull Location location, int time, @NotNull org.bukkit.Color color, int transparency);
No override with text and bukkit color?

2022-07-27 19:15 UTC, BillyGalbreath approved these changes

2022-07-29 07:03 UTC, merged