feat: honey bottle cures and heals
pl3xgaming/Purpur pull request #1146
Opened 2022-10-06 08:48 UTC by RealRONiN

Honey bottles can cure any effect same as milk bukkets, it can also heal a player and add additional potion effects if any specified.
IRL Honey has numerous benefits, it'd make sense if it serves more benefits than just the saturation effect.

2022-10-06 09:51 UTC, RealRONiN commented
I'm not sure what to do with this, https://github.com/PurpurMC/Purpur/blob/c27e67a4a830c1c9c003a4da80226a5f98bf6d95/patches/server/0309-Honey-bottle-cures-and-heals.patch#L32

2022-10-06 13:01 UTC, BillyGalbreath requested changes
I just woke up, so I hope I got it all in one go ^_^

2022-10-06 13:01 UTC, BillyGalbreath commented on patches/server/0309-Honey-bottle-cures-and-heals.patch
> ++    public List<MobEffect> honeyBottleCurableEffects = new ArrayList<>();
I suggest using the word remove instead of cure/curable in the name (`honeyBottleRemoveEffects` here, and `remove-effects` below). It goes with the `add` option better, imo.

2022-10-06 13:01 UTC, BillyGalbreath commented on patches/server/0309-Honey-bottle-cures-and-heals.patch
> ++    public List<MobEffect> honeyBottleAddedEffects = new ArrayList<>();
If you change this to a Map<MobEffect,Integer> we can have per-effect durations and can get rid of the extra `honeyBottlePotionEffectsDuration` option.

2022-10-06 13:01 UTC, BillyGalbreath commented on patches/server/0309-Honey-bottle-cures-and-heals.patch
> ++            add("minecraft:bad_omen");
Make this only contain vanilla behavior (only removes poison), then you can get rid of the extra `honeyBottleCures` option above.

2022-10-06 13:01 UTC, BillyGalbreath commented on patches/server/0309-Honey-bottle-cures-and-heals.patch
> ++            add("minecraft:glowing");
Make this only contain vanilla behaviors (empty section), then you can get rid of the extra `honeyBottleAddsPositiveEffects` option above.

2022-10-06 13:01 UTC, BillyGalbreath commented on patches/server/0309-Honey-bottle-cures-and-heals.patch
> +             user.removeEffect(MobEffects.POISON, org.bukkit.event.entity.EntityPotionEffectEvent.Cause.FOOD); // Paper
You can get rid of this line entirely. Just be sure poison is in the default options. That way if someone wants they could actually remove it from being curable.

2022-10-08 06:58 UTC, RealRONiN commented on patches/server/0309-Honey-bottle-cures-and-heals.patch
> +             user.removeEffect(MobEffects.POISON, org.bukkit.event.entity.EntityPotionEffectEvent.Cause.FOOD); // Paper
Moved it to defualt food properties

2022-10-08 07:04 UTC, RealRONiN commented
Technically, milk bukket should be a food item, should I add it to `Foods` class and move MilkBukketItem class's properties to it?

2022-10-10 08:05 UTC, RealRONiN commented
https://discord.com/channels/685683385313919172/720374890472931328/1028914991421726730

2022-10-25 09:58 UTC, granny approved these changes
PR is ready to merge. Waiting on Billy in case he wants to make any changes.

2022-10-26 16:21 UTC, BillyGalbreath requested changes
This is _far_ from ready. I will rewrite it myself when I get back online.

2023-01-20 04:49 UTC, granny commented
Closing as it doesn't seem like there will be any progress done anytime soon.

2023-01-20 04:49 UTC, closed without merging