Milk keeps beneficial effects
pl3xgaming/Purpur pull request #1147
Opened 2022-10-06 18:20 UTC by RhythmicSys

This option allows for milk to clear negative effects, while keeping beneficial ones.
This will not clear bad omen, if `milk-cures-bad-omen` is set to false.

2022-10-07 16:41 UTC, BillyGalbreath requested changes

2022-10-07 16:41 UTC, BillyGalbreath commented on patches/server/0309-Milk-keeps-beneficial-effects.patch
> ++                }
This whole block feels over complicated. Can't we just iterate the `activeEffects` once and do the removing inside that?

2022-10-07 16:41 UTC, BillyGalbreath commented on patches/server/0309-Milk-keeps-beneficial-effects.patch
> ++import java.util.Collection;
inline the imports ;)

2022-10-07 17:06 UTC, RhythmicSys commented on patches/server/0309-Milk-keeps-beneficial-effects.patch
> ++                }
Tried to do 
```java
if (!world.purpurConfig.milkClearsBeneficialEffects && !activeEffects.isEmpty()){
                for (MobEffectInstance effect : activeEffects){
                    if(!effect.getEffect().isBeneficial()){
                        MobEffect mobEffect = effect.getEffect();
                        user.removeEffect(mobEffect);
                    }
                }
            }
```

And
```java
if (!world.purpurConfig.milkClearsBeneficialEffects && !activeEffects.isEmpty()){
                for (MobEffectInstance effect : activeEffects){
                    if(!effect.getEffect().isBeneficial()){
                      user.removeEffect(effect.getEffect());
                    }
                }
            }
```
but both gave me 
```console
[09:59:50 WARN]: Failed to handle packet for /[0:0:0:0:0:0:0:1%0]:55380
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:769) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:380) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:588) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1594) ~[purpur-1.19.2.jar:git-Purpur-"46441eb"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-"46441eb"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-"46441eb"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-"46441eb"]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-"46441eb"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1625) ~[?:?]
	at net.minecraft.world.item.MilkBucketItem.finishUsingItem(MilkBucketItem.java:41) ~[?:?]
	at net.minecraft.world.item.ItemStack.finishUsingItem(ItemStack.java:504) ~[purpur-1.19.2.jar:git-Purpur-"46441eb"]
	at net.minecraft.world.entity.LivingEntity.completeUsingItem(LivingEntity.java:4002) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.completeUsingItem(ServerPlayer.java:1762) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.updateUsingItem(LivingEntity.java:3852) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.updateUsingItem(ServerPlayer.java:2413) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.updatingUsingItem(LivingEntity.java:3833) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3019) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:308) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:683) ~[?:?]
	... 9 more
```

2022-10-08 23:39 UTC, BillyGalbreath approved these changes

2022-10-08 23:54 UTC, merged