Add new permissions and register some existing ones
pl3xgaming/Purpur pull request #1157
Opened 2022-10-14 03:18 UTC by RhythmicSys

Adds permission `purpur.mending_shift_click` as requested in [Discussion 1088](https://github.com/PurpurMC/Purpur/discussions/1088)
Adds permission `purpur.inventory_totem` as requested in [Discussion 1101](https://github.com/PurpurMC/Purpur/discussions/1101)
Adds permission `purpur.anvil.format` as requested in [Discussion 666](https://github.com/PurpurMC/Purpur/discussions/666)

Registered `purpur.anvil.minimessage` and `purpur.anvil.remove_italics` properly, and set default to `FALSE`
No longer require `purpur.anvil.color` to use minimessage, remove_italics, or format

2022-10-14 06:46 UTC, YouHaveTrouble requested changes

2022-10-14 06:46 UTC, YouHaveTrouble commented on patches/server/0310-Add-Additional-Permissions.patch
> ++import org.bukkit.craftbukkit.entity.CraftHumanEntity;
rogue import. use static org.bukkit.craftbukkit.entity.CraftHumanEntity where you use it

2022-10-14 06:58 UTC, RhythmicSys commented on patches/server/0310-Add-Additional-Permissions.patch
> ++import org.bukkit.craftbukkit.entity.CraftHumanEntity;
imports are my downfall

2022-10-14 07:05 UTC, YouHaveTrouble approved these changes

2022-10-15 02:53 UTC, granny approved these changes

2022-10-15 03:01 UTC, merged