Add PreExplodeEvents
pl3xgaming/Purpur pull request #1234
Opened 2022-12-26 22:44 UTC by SageSphinx63920

This pr add PreXExplodeEvents to cancel an explosion before Minecraft calculates all the changes to prevent lag spikes

2022-12-26 22:59 UTC, JanTuck commented on patches/api/0057-Add-PreExplodeEvents.patch
> ++++ b/src/main/java/org/purpurmc/purpur/event/entity/GoatRamEntityEvent.java
What about this?

2022-12-26 23:00 UTC, JanTuck commented
How is this different from this? https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/ExplosionPrimeEvent.html

2022-12-26 23:03 UTC, SageSphinx63920 commented
We talked about this on the Discord. This event gets called before any calculation of the radius is happing. If you spawn a creeper with a really big explosion radius and cancel the explosion event, the game still calculates every block that needs to be destroyed, which drops the TPS. You can cancel this event to prevent this

2022-12-26 23:04 UTC, SageSphinx63920 commented on patches/api/0057-Add-PreExplodeEvents.patch
> ++++ b/src/main/java/org/purpurmc/purpur/event/entity/GoatRamEntityEvent.java
I don't know? I was just editing purpur like normal and after I rebuild my patches this appeared?

2022-12-26 23:04 UTC, JanTuck commented
Alright thx.

2023-01-20 05:46 UTC, SageSphinx63920 commented
Do to Billy might not reviewing this, can somebody else do?

2023-01-22 20:36 UTC, granny requested changes
Since the params & everything is almost identical, have you thought about just extending the `BlockExplodeEvent` event instead of `BlockEvent`?

2023-01-22 20:36 UTC, granny commented on patches/server/0310-Add-PreExplodeEvents.patch
> ++import org.purpurmc.purpur.event.entity.PreEntityExplodeEvent;
inline import

2023-01-22 20:36 UTC, granny commented on patches/api/0057-Add-PreExplodeEvents.patch
> ++    public PreBlockExplodeEvent(@NotNull final Block what, final float yield) {
might as well include the exploded blockstate as a parameter to the event like in `BlockExplodeEvent`. Include another constructor as well.

2023-03-01 01:57 UTC, granny commented
@SageSphinx63920 any updates? do you need help rebasing the branch?

2023-03-02 01:05 UTC, granny approved these changes

2023-03-02 01:07 UTC, merged