Add options to disable tripwire hook and leave decay updates
pl3xgaming/Purpur pull request #1297
Opened 2023-03-22 20:45 UTC by SageSphinx63920

This pr adds config option to disable both things.

2023-03-22 20:45 UTC, SageSphinx63920 commented
I pr on the docs when this is approved

2023-03-22 20:52 UTC, SageSphinx63920 commented
The action fails, because the pufferfish patch did smith bad. Running `./gradlew applyPatches` works fine and `./gradlew runDev` works also without any errors

2023-03-26 09:22 UTC, granny requested changes
Remove the `disable-leaves-decay-updates` option completely, it's unneeded.

Your changes to `TripWireBlock` don't do what you think it does. Remove what you have and take inspiration from the other changes in this patch.

Hint: all public overridden methods that are meant to return a `BlockState` include a check that returns a default blockstate of the block.

2023-03-26 09:22 UTC, granny commented on patches/server/0083-Add-option-to-disable-certain-block-updates.patch
> +
unneeded since you can set `persistent` to the blockstate to stop it from decaying

2023-03-26 09:22 UTC, granny commented on patches/server/0083-Add-option-to-disable-certain-block-updates.patch
> +         boolean flag1 = false;
not placed in the correct methods

2023-03-26 09:26 UTC, granny commented
> The action fails, because the pufferfish/some random patch before it patch did smth bad. Running `./gradlew applyPatches` works fine and `./gradlew runDev` works also without any errors

should be fine once you merge changes from `ver/1.19.4`

2023-04-06 20:42 UTC, granny commented
any updates? this pull request will be closed if it continues to be stale

2023-04-06 21:44 UTC, SageSphinx63920 commented
Yeah sorry granny, I need to be reminded that sth like this exits bc I forgot about it. Ill fix it tomorrow

2023-05-16 19:39 UTC, closed without merging