Stored Bee API
pl3xgaming/Purpur pull request #1343
Opened 2023-06-11 00:34 UTC by EOT3000

Adds a way to modify some properties of individual stored entities (bees in beehive), as well as release them individually, without having to release them all.

With requested changes.

2023-06-11 17:44 UTC, theomega24 requested changes
The whitespace stuff is largely just to make the diff smaller and more maintainable for us, nothing against your code style.

2023-06-11 17:44 UTC, theomega24 commented on patches/server/0307-Stored-Bee-API.patch
> ++        if (!list.isEmpty()) {
Is the list ever modified?

2023-06-11 17:44 UTC, theomega24 commented on patches/server/0307-Stored-Bee-API.patch
> ++        loadInitialBees();
This function call can be inlined

2023-06-11 17:44 UTC, theomega24 commented on patches/server/0307-Stored-Bee-API.patch
> ++            // Purpur - change which releaseBees method is called, and use beehive snapshot
Use `// Purpur start` and `// Purpur end` for multiline changes

2023-06-11 17:44 UTC, theomega24 commented on patches/server/0307-Stored-Bee-API.patch
> ++
Small nitpick, but remove extra whitespace

2023-06-11 17:44 UTC, theomega24 commented on patches/server/0307-Stored-Bee-API.patch
> ++
Small nitpick, but remove extra whitespace

2023-06-11 17:44 UTC, theomega24 commented on patches/server/0307-Stored-Bee-API.patch
> ++
Small nitpick, but remove extra whitespace

2023-06-11 17:44 UTC, theomega24 commented on patches/server/0307-Stored-Bee-API.patch
> ++
Small nitpick, but remove extra whitespace

2023-06-11 17:44 UTC, theomega24 commented on patches/server/0307-Stored-Bee-API.patch
> ++
Small nitpick, but remove extra whitespace

2023-06-11 17:44 UTC, theomega24 commented on patches/server/0307-Stored-Bee-API.patch
> ++
Small nitpick, but remove extra whitespace

2023-06-11 17:44 UTC, theomega24 commented on patches/server/0307-Stored-Bee-API.patch
> ++
Small nitpick, but remove extra whitespace

2023-06-11 17:44 UTC, theomega24 commented on patches/api/0051-Stored-Bee-API.patch
> ++
Small nitpick, but remove extra whitespace

2023-06-11 17:44 UTC, theomega24 commented on patches/server/0307-Stored-Bee-API.patch
> ++
Small nitpick, but remove extra whitespace

2023-06-11 17:44 UTC, theomega24 commented on patches/server/0307-Stored-Bee-API.patch
> ++
Small nitpick, but remove extra whitespace

2023-06-11 18:00 UTC, EOT3000 commented on patches/server/0307-Stored-Bee-API.patch
> ++        if (!list.isEmpty()) {
List is passed to BeehiveBlockEntity.releaseBee, and the vanilla method will modify it.

2023-06-12 22:40 UTC, EOT3000 commented
Done.

2023-06-26 01:08 UTC, granny approved these changes
LGTM. For future reference make sure to create a new branch specifically for the PR you're creating instead of committing directly to the `ver/...` branch.

2023-06-26 01:09 UTC, merged