Shears can defuse TNT
pl3xgaming/Purpur pull request #1372
Opened 2023-07-02 00:04 UTC by MrFishCakes

TNT can now be defused when right clicking with shears, nothing more to it than an additional gameplay mechanic. 

Option is per-world and a value of 0.00 disables the function. See patch commit for a few more details

2023-07-02 00:10 UTC, granny requested changes
Currently on mobile so i can't look into the implementation, so nitpicking for now until I can take a better look. Patch diffs should touch as little as possible to lower the maintenance burden of each patch.

2023-07-02 00:10 UTC, granny commented on patches/server/0306-Shears-can-defuse-TNT.patch
> +-import net.minecraft.world.level.Explosion;
needs to be reverted

2023-07-02 00:10 UTC, granny commented on patches/server/0306-Shears-can-defuse-TNT.patch
> +-import java.util.Locale;
needs to be reverted.

2023-07-02 01:13 UTC, MrFishCakes commented
Both been reverted. Didn't pick up on this during committing!

2023-07-03 03:33 UTC, granny approved these changes
LGTM :)

All that's left is to document the config option and permission in the docs (https://github.com/purpurMC/purpurdocs) and the patch will be merged!

2023-07-03 23:08 UTC, merged