Add SIMD Support for Java 21
pl3xgaming/Purpur pull request #1499
Opened 2024-03-06 06:50 UTC by rockfordroeNG

See: https://github.com/pufferfish-gg/Pufferfish/issues/81#issuecomment-1873195837

2024-03-06 07:28 UTC, granny requested changes
Move to the respective `###-Fix-pufferfish-issues.patch` in the `api/` and `server/` patch directories.

Please also PR this to Pufferfish. If Kevin doesn't merge your PR, doesn't update Pufferfish with this change, or doesn't comment on your PR after some weeks pass, then I'll merge this PR.

2024-03-07 08:55 UTC, rockfordroeNG commented
Requested changes have been made. A pr to pufferfish has just been filed.

2024-03-30 21:42 UTC, SrBedrock commented
> Please also PR this to Pufferfish. If Kevin doesn't merge your PR, doesn't update Pufferfish with this change, or doesn't comment on your PR after some weeks pass, then I'll merge this PR.

@granny has enough time passed?

2024-03-31 08:02 UTC, granny approved these changes

2024-03-31 08:02 UTC, merged