Config for Enderman to target spawned Endermites
pl3xgaming/Purpur pull request #190
Opened 2021-03-07 22:00 UTC by Encode42

Allows Enderman to target Endermites that were spawned using a command or Spawn Egg.

[Video](https://cdn.discordapp.com/attachments/720374890472931328/818240604437086208/2021-03-07_16.55.15.mp4)

2021-03-07 22:16 UTC, Encode42 commented
Draft PR since I want to add a few other Enderman-related options.

2021-03-07 22:56 UTC, Encode42 commented
Tested and ready for review.

2021-03-09 21:03 UTC, BillyGalbreath requested changes
These should be 3 different patches, since each one is a separate mechanic on their own.

2021-03-09 21:24 UTC, BillyGalbreath approved these changes

2021-03-09 21:25 UTC, merged