Allows to display progress messages by player instead to everyone on the server.
pl3xgaming/Purpur pull request #312
Opened 2021-05-02 23:37 UTC by DoctaEnkoda

When a server has a lot of people, player advancements spam the chat, a lot of servers turn it off to make the chat clean.
My patch allows to keep it on the server but by sending it only to the player concerned and not to the whole server.

2021-05-02 23:39 UTC, notOM3GA requested changes

2021-05-02 23:39 UTC, notOM3GA commented on patches/server/0206-Allows-to-display-progress-messages-by-player-instea.patch
> ++                    ChatMessage advancementMessage = new ChatMessage("chat.type.advancement." + advancement.c().e().a(), this.player.getScoreboardDisplayName(), advancement.j());
add OBFHELPERs

2021-05-02 23:39 UTC, notOM3GA commented on patches/server/0206-Allows-to-display-progress-messages-by-player-instea.patch
> ++                        this.player.sendMessage(advancementMessage, SystemUtils.b);
add OBFHELPERs

2021-05-02 23:39 UTC, notOM3GA commented on patches/server/0206-Allows-to-display-progress-messages-by-player-instea.patch
> ++                        this.e.sendMessage(advancementMessage, ChatMessageType.SYSTEM, SystemUtils.b);
add OBFHELPERs

2021-05-02 23:39 UTC, notOM3GA commented on patches/server/0206-Allows-to-display-progress-messages-by-player-instea.patch
> ++        advancementMessageByPlayer = getBoolean("settings.advancement.message-by-player", advancementMessageByPlayer);
this could probably do with a better name but i'm too tired to think of one

2021-05-02 23:44 UTC, BillyGalbreath commented on patches/server/0206-Allows-to-display-progress-messages-by-player-instea.patch
> ++        advancementMessageByPlayer = getBoolean("settings.advancement.message-by-player", advancementMessageByPlayer);
```suggestion
+        advancementOnlyBroadcastToAffectedPlayer = getBoolean("settings.advancement.only-broadcast-to-affected-player", advancementOnlyBroadcastToAffectedPlayer);
```

2021-05-03 00:19 UTC, notOM3GA requested changes

2021-05-03 00:19 UTC, notOM3GA commented on patches/server/0206-Allows-to-display-progress-messages-by-player-instea.patch
> ++    public ChatMessage getMessagePlayerAdvancement(Advancement advancement) { return new ChatMessage("chat.type.advancement." + advancement.c().e().a(), this.player.getScoreboardDisplayName(), advan
this isn't an OBFHELPER. you can use any mappings to create an OBFHELPER for `advancement.c().e().a()` and `advancement.j()`

2021-05-03 00:19 UTC, notOM3GA commented on patches/server/0206-Allows-to-display-progress-messages-by-player-instea.patch
> ++                        this.player.sendMessage(getMessagePlayerAdvancement(advancement), SystemUtils.b);
OBFHELPER for SystemUtils.b

2021-05-03 00:19 UTC, notOM3GA commented on patches/server/0206-Allows-to-display-progress-messages-by-player-instea.patch
> ++                        this.e.sendMessage(getMessagePlayerAdvancement(advancement), ChatMessageType.SYSTEM, SystemUtils.b);
OBFHELPER for SystemUtils.b and for this.e

2021-05-03 13:33 UTC, notOM3GA requested changes

2021-05-03 13:33 UTC, notOM3GA commented on patches/server/0206-Allows-to-display-progress-messages-by-player-instea.patch
> ++    public String advancementType() { return  a(); } // Purpur - OBFHELPER
rename to `getName()`

2021-05-03 13:33 UTC, notOM3GA commented on patches/server/0206-Allows-to-display-progress-messages-by-player-instea.patch
> ++    public IChatBaseComponent getJ() { return j(); } // Purpur - OBFHELPER
rename to `getChatComponent()`

2021-05-03 15:07 UTC, DoctaEnkoda commented
It's good

2021-05-03 15:21 UTC, notOM3GA approved these changes

2021-05-03 15:22 UTC, merged