[meta] Update Contributing.md to reflect new naming
pl3xgaming/Purpur pull request #337
Opened 2021-05-16 02:00 UTC by TwoLeggedCat

Also fixes somewhere where "Paper" should say "Purpur," so please fix that if you close this PR without merging :)

2021-05-16 05:46 UTC, BillyGalbreath requested changes

2021-05-16 05:46 UTC, BillyGalbreath commented on CONTRIBUTING.md
> +We are trying to use a new naming system where all (or most) commits pushed to master are prefixed with a tag like `[feat]`, `[fix]`, `[meta]`, etc and would appreciate if this were done in PR titles
Commits aren't that important, imho. It's the patch files/headers that are important.
```suggestion
We are trying to use a new naming system where all (or most) patches are prefixed with a tag like `[feat]`, `[fix]`, `[meta]`, etc and would appreciate if this were done in PR titles as well. While this is by no means a requirement, it allows users to see what's in a new build without reading the commit or even the entire message, and makes it easier to find a specific commit as well.
```

2021-05-16 14:09 UTC, famous1622 commented
I'd avoid naming patches with brackets if it makes the file names weird, iirc NTFS doesn't like them.

2021-05-16 14:11 UTC, notOM3GA commented
it wont affect the file names, git patching omits special characters for the file name

2021-05-16 15:56 UTC, TwoLeggedCat commented on CONTRIBUTING.md
> +We are trying to use a new naming system where all (or most) commits pushed to master are prefixed with a tag like `[feat]`, `[fix]`, `[meta]`, etc and would appreciate if this were done in PR titles
As long as the merger renames the squashed commit appropriately so it shows on the downloads page; will change

2021-05-16 22:55 UTC, granny commented on CONTRIBUTING.md
> +We are trying to use a new naming system where all (or most) patches are prefixed with a tag like `[feat]`, `[fix]`, `[meta]`, etc and would appreciate if this were done in PR titles as well. While t
```suggestion
### Naming your Patches/PRs
We use a naming system with a similar concept to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).

Patches are prefixed with a type (`[feat]`, `[fix]`, `[meta]`, `[refactor]`, `[perf]`). The type should also appear in your PR title. 

This lets us:
* know what type of PR it is
* know what the patches do at a glance
* categorize the patches
```

2021-05-16 23:32 UTC, TwoLeggedCat commented on CONTRIBUTING.md
> +We are trying to use a new naming system where all (or most) patches are prefixed with a tag like `[feat]`, `[fix]`, `[meta]`, etc and would appreciate if this were done in PR titles as well. While t
"This lets us" -> "This lets us and our users?"

2021-05-16 23:33 UTC, granny commented on CONTRIBUTING.md
> +We are trying to use a new naming system where all (or most) patches are prefixed with a tag like `[feat]`, `[fix]`, `[meta]`, etc and would appreciate if this were done in PR titles as well. While t
edited

2021-05-16 23:35 UTC, granny commented
This should be merged once all the patches follow the naming system.

2021-05-16 23:35 UTC, granny approved these changes

2021-09-09 17:28 UTC, Oharass approved these changes
LGTM

2021-10-08 13:24 UTC, granny commented
merged into #351

2021-10-08 13:24 UTC, closed without merging