Make anvil cumulative cost configurable
pl3xgaming/Purpur pull request #352
Opened 2021-05-21 15:13 UTC by 12emin34

XP cost of the anvil gets higher each time an item is used in the anvil
https://minecraft.fandom.com/wiki/Anvil_mechanics#Costs_for_combining_enchantments
This patch adds an option to toggle the cumulative cost increase

2021-05-21 15:18 UTC, BillyGalbreath approved these changes

2021-05-21 18:29 UTC, YouHaveTrouble commented
I believe this can be done via anvil API with a plugin

2021-05-21 18:53 UTC, granny approved these changes

2021-05-24 01:12 UTC, notOM3GA requested changes

2021-05-24 01:12 UTC, notOM3GA commented on patches/server/0219-Make-anvil-cumulative-cost-configurable.patch
> ++import net.pl3x.purpur.PurpurConfig;
unnecessary import, use fqdn

2021-05-24 01:12 UTC, notOM3GA commented on patches/server/0219-Make-anvil-cumulative-cost-configurable.patch
> +-import net.minecraft.locale.LocaleLanguage;
don't touch this import, thanks

2021-05-25 19:09 UTC, notOM3GA approved these changes

2021-05-25 19:09 UTC, merged