Allows to display the death message only per player
pl3xgaming/Purpur pull request #363
Opened 2021-05-26 00:52 UTC by DoctaEnkoda

As done for advancements, I submit the same method for broadcast death message.

2021-05-26 00:55 UTC, granny commented
Might as well combine this with the broadcast advancements patch I feel like

2021-05-26 01:02 UTC, notOM3GA commented
yes merge into the same patch please

2021-05-26 03:01 UTC, DoctaEnkoda commented
its fine

2021-05-26 10:16 UTC, notOM3GA requested changes

2021-05-26 10:16 UTC, notOM3GA commented on patches/server/0206-Allows-change-broadcast-message-by-player.patch
> ++                        this.server.getPlayerList().a((EntityHuman) this, ichatbasecomponent);
OBFHELPER for `a`

2021-05-26 10:16 UTC, notOM3GA commented on patches/server/0206-Allows-change-broadcast-message-by-player.patch
> ++                        this.server.getPlayerList().b(this, ichatbasecomponent);
OBFHELPER for `b`

2021-05-26 19:46 UTC, notOM3GA approved these changes

2021-05-28 03:45 UTC, BillyGalbreath requested changes

2021-05-28 03:45 UTC, BillyGalbreath commented on patches/server/0206-Allows-change-broadcast-message-by-player.patch
> ++        deathMessageOnlyBroadcastToAffectedPlayer = getBoolean("settings.death.only-broadcast-to-affected-player", deathMessageOnlyBroadcastToAffectedPlayer);
i think we should group these settings in the config like you did in code. `settings.broadcasts.whatever` or something. open to suggestions.

2021-05-28 03:50 UTC, DoctaEnkoda commented on patches/server/0206-Allows-change-broadcast-message-by-player.patch
> ++        deathMessageOnlyBroadcastToAffectedPlayer = getBoolean("settings.death.only-broadcast-to-affected-player", deathMessageOnlyBroadcastToAffectedPlayer);
Yes I think it will be better, I will do it right after in the next hour.

2021-05-28 04:08 UTC, DoctaEnkoda commented
Its fine

2021-05-28 04:53 UTC, BillyGalbreath approved these changes

2021-05-28 18:25 UTC, notOM3GA approved these changes

2021-05-28 18:25 UTC, merged