Config MobEffect by world
pl3xgaming/Purpur pull request #369
Opened 2021-05-31 09:09 UTC by DoctaEnkoda

2021-05-31 13:56 UTC, notOM3GA requested changes

2021-05-31 13:56 UTC, notOM3GA commented on patches/server/0224-Config-MobEffect-by-world.patch
> ++    public void tick(EntityLiving entityliving, int i) { tickMobEffects(entityliving, i); } public void tickMobEffects(EntityLiving entityliving, int amplifier) { // Purpur - OBFHELPERS
you dont need to put an OBFHELPER here as it already has a name

2021-05-31 17:44 UTC, DoctaEnkoda commented on patches/server/0224-Config-MobEffect-by-world.patch
> ++    public void tick(EntityLiving entityliving, int i) { tickMobEffects(entityliving, i); } public void tickMobEffects(EntityLiving entityliving, int amplifier) { // Purpur - OBFHELPERS
OBFHELPER remove

2021-05-31 19:25 UTC, notOM3GA requested changes

2021-05-31 19:25 UTC, notOM3GA commented on patches/server/0224-Config-MobEffect-by-world.patch
> ++    public void tick(EntityLiving entityliving, int i) { tickMobEffects(entityliving, i); } public void tickMobEffects(EntityLiving entityliving, int amplifier) { // Purpur
you dont need any of the changes on this line

2021-06-01 17:05 UTC, notOM3GA approved these changes

2021-06-02 01:31 UTC, BillyGalbreath approved these changes

2021-06-02 01:31 UTC, merged