Custom Enchantment API
pl3xgaming/Purpur pull request #401
Opened 2021-06-22 21:52 UTC by NickAcPT

This PR aims to allow plugins that depend on the Purpur API to create custom `NamespaceKey` based enchantments.

As it's clear by the PR status, this is still very much WIP and I'd like to receive feedback along the way. More so when it comes to git stuff, as I'm not very used to rebasing and reordering commits.

# Goals

There are a few goals that I want this PR to achieve before it gets merged:

- [ ] Allow plugins to add custom enchantments with the Bukkit API
- [ ] Allow plugins to query and interact with custom enchantments without having to query new APIs (interop with old bukkit enchantments API)
- [ ] Allow players to apply custom enchantments with the vanilla enchant command (vanilla interop)
- [ ] Make sure not to break other custom enchantment plugins

# Considerations

Since this feature is supposed to be flexible for a lot of use-cases, there are some things that need to be considered:

- [ ] The package where the code resides. *Is `org.bukkit.enchantments.custom` even good enough?* *Should it be on a Purpur package?*

- [ ] API structure. Should plugins have to implement a separate interface or extend from a Bukkit class? *Should our `CustomEnchantment` class/interface extend/implement any Bukkit class/interface?*

- [ ] How to show it for clients. *Show custom enchantments follow the same layout as regular enchantments?* *Should this change introduce a way to modify the layout of the enchantments as a configuration setting?*

- [ ] Anvil support. *Does Vanilla even handle custom enchantments well with Anvils?* *What about books?* *Can we apply custom enchantments to items with an anvil?* *What about enchantment merging?*

- [ ] Exposing enchantments properly. *Is this API flexible enough for anyone to use it?* *What about when enchantments need Listeners to function?*

2021-06-22 21:53 UTC, notOM3GA requested changes

2021-06-22 21:53 UTC, notOM3GA commented on patches/api/0042-Custom-enchantments-API.patch
> ++package org.bukkit.enchantments.custom;
use the purpur package

2021-06-24 21:23 UTC, NickAcPT commented
Please excuse the inactivity. I am still working on this, just not here.

This is mainly because I don't have a lot of experience with Git when it comes to properly working with patches and merging them when they get added to the main branch.

While working on this, I somehow managed to locally reorder commits when merging from upstream.

Sadly, there's not much documentation regarding this (things like making sure that patches are up-to-date and properly applied while working on a PR on a separate branch), and there's no way for me to get in contact to get proper support for this.

2021-06-25 10:47 UTC, NickAcPT commented
Okay, I made some progress regarding custom enchantments:

https://user-images.githubusercontent.com/32451103/123413329-8eb03000-d5aa-11eb-9399-357d526c419a.mp4

But before I can move any further, I need to ask the team (mainly @BillyGalbreath @jpenilla) about their thoughts on this PR.

Will this get merged once it's finished, or is it something that will be on hold forever (Paper moment™)? What is the general opinion of the team regarding this?

I remember speaking earlier with Billy and it appeared that they were okay with this PR, but I just want confirmation if that is still the case.

2021-06-25 10:57 UTC, notOM3GA commented
This PR looks great so far, I'm excited to see what you create. As a member of the team, I think that you should keep going on this PR and that it will almost definitely get merged (with some critique).

2021-06-25 11:12 UTC, NickAcPT commented
Oops, accidentally closed this by mistake when I reset with Purpur's branch

2021-06-25 12:53 UTC, NickAcPT commented on patches/server/0213-Custom-Enchantment-API.patch
> ++                // Purpur end
I understand that this might be a bit "sketchy", if there's any other ideas that don't involve me messing with raw NBT, let me know.

2021-06-25 12:54 UTC, NickAcPT commented on patches/server/0213-Custom-Enchantment-API.patch
> ++                // Purpur end
I understand that this might be a bit "sketchy", if there's any other ideas that don't involve me messing with raw NBT, let me know.

2021-06-25 12:55 UTC, NickAcPT commented on patches/server/0213-Custom-Enchantment-API.patch
> ++        }).then(Commands.argument("targets", EntityArgument.entities()).then(Commands.argument("enchantment", ItemEnchantmentArgument.enchantment()).suggests(SUGGEST_ENCHANTMENTS).executes((context)
This change is required to let the client know that the server is proving the completion. Client still shows command in red, although the enchantment is valid server-side.
![image](https://i.imgur.com/gY9IGzk.png)

2021-06-25 12:56 UTC, NickAcPT commented on patches/server/0213-Custom-Enchantment-API.patch
> ++        }
This was added to bring the EnchantmentCategory enum into parity with it's NMS version

2021-06-25 12:57 UTC, NickAcPT commented on patches/server/0213-Custom-Enchantment-API.patch
> ++    public final static net.kyori.adventure.text.Component customEnchantmentMagicSuffix = net.kyori.adventure.text.Component.space().color(TextColor.color(0xfa02ff)).append(net.kyori.adventure.text.
This is a bit questionable, I know.
This is here because the lore needs to be filtered when reading items because creative players override the items on the server when interacting with them.

2021-06-29 00:55 UTC, YouHaveTrouble commented on patches/server/0213-Custom-Enchantment-API.patch
> ++        }).then(Commands.argument("targets", EntityArgument.entities()).then(Commands.argument("enchantment", ItemEnchantmentArgument.enchantment()).suggests(SUGGEST_ENCHANTMENTS).executes((context)
You will probably have to edit brigadier node for enchant command and redo the argument completion for that specific argument. Shouldn't be too hard afaik

2021-06-29 01:09 UTC, YouHaveTrouble commented on patches/server/0213-Custom-Enchantment-API.patch
> ++    public final static net.kyori.adventure.text.Component customEnchantmentMagicSuffix = net.kyori.adventure.text.Component.space().color(TextColor.color(0xfa02ff)).append(net.kyori.adventure.text.
Maybe see where creative packets are parsed and do some funky filtering logic there? Seems like filtering this out asap could be a good idea, would love some input from others tho.

2021-07-01 11:21 UTC, NickAcPT commented on patches/server/0213-Custom-Enchantment-API.patch
> ++    public final static net.kyori.adventure.text.Component customEnchantmentMagicSuffix = net.kyori.adventure.text.Component.space().color(TextColor.color(0xfa02ff)).append(net.kyori.adventure.text.
Items and read and written to the protocol in multiple places.
I think having the filtering/processing being done everywhere is for the best since that means that we only have to do it in one central place. I'll be waiting for other reviewers to get their opinion on this.

(cc: @YouHaveTrouble)

2021-08-22 02:59 UTC, NickAcPT commented
Closing PR as development of these changes are now being done downstream.

2021-08-22 02:59 UTC, closed without merging