Add Option for disable observer clocks
pl3xgaming/Purpur pull request #486
Opened 2021-07-10 00:23 UTC by DoctaEnkoda

Allow to disable observer clocks: https://www.spigotmc.org/attachments/observerclock-gif.365936/

2021-07-10 00:40 UTC, notOM3GA requested changes

2021-07-10 00:40 UTC, notOM3GA commented on patches/server/0232-Add-Option-for-disable-observer-clocks.patch
> ++        // Purpur Stop
end not stop

2021-07-10 01:58 UTC, DoctaEnkoda commented on patches/server/0232-Add-Option-for-disable-observer-clocks.patch
> ++        // Purpur Stop
oh my bad sorry ^^

2021-07-14 12:28 UTC, notOM3GA requested changes

2021-07-14 12:28 UTC, notOM3GA commented on patches/server/0232-Add-Option-for-disable-observer-clocks.patch
> ++                neighborState.getValue(ObserverBlock.FACING).getOpposite() != direction)) {
while putting parts of the if statement on a new line help for readability, it makes updating harder. please keep if statements on the same line ^_^

2021-07-14 14:05 UTC, DoctaEnkoda commented on patches/server/0232-Add-Option-for-disable-observer-clocks.patch
> ++                neighborState.getValue(ObserverBlock.FACING).getOpposite() != direction)) {
It is modified, and indeed that will make it possible to modify it better. I just thought it was a very long line on my IDE.

2021-07-15 01:06 UTC, notOM3GA approved these changes

2021-07-22 23:48 UTC, DoctaEnkoda commented
up

2021-08-06 07:43 UTC, merged