UPnP Port Forwarding
pl3xgaming/Purpur pull request #489
Opened 2021-07-11 14:26 UTC by notOM3GA

This pull request allows people with supported routers to use UPnP to automatically port forward (part of #478).

I was unable to test this as my router doesn't support UPnP, so if anyone who can use UPnP would test it that would be nice.

2021-07-14 11:13 UTC, mikroskeem requested changes
There are more logger nitpicks, ones I pointed out should be good examples to fix remaining.

2021-07-14 11:13 UTC, mikroskeem commented on patches/server/0232-UPnP-Port-Forwarding.patch
> ++                LOGGER.info("[UPnP] Port " + this.getPort() + " closed");
`LOGGER.info("[UPnP] Port {} closed", this.getPort());`

2021-07-14 11:13 UTC, mikroskeem commented on patches/server/0232-UPnP-Port-Forwarding.patch
> ++                LOGGER.error("[UPnP] Failed to close port " + this.getPort());
`LOGGER.error("[UPnP] Failed to close port {}", this.getPort());`

2021-07-14 11:13 UTC, mikroskeem commented on patches/server/0232-UPnP-Port-Forwarding.patch
> ++            LOGGER.info("[UPnP] Attempting to start UPnP port forwarding service...");
`LOGGER.info("[UPnP] Starting UPnP port forwarding service");`

2021-07-15 09:08 UTC, ATMmachin3 commented
Question:
Does this utilise the port the server has been set to use or only the default port?

2021-07-15 20:29 UTC, notOM3GA commented
the port the server has been set to you

2021-09-09 17:31 UTC, Oharass requested changes

2021-09-09 17:31 UTC, Oharass commented on patches/server/0232-UPnP-Port-Forwarding.patch
> ++    protected boolean upnp = false; // Purpur
comments

2021-09-09 17:32 UTC, Oharass approved these changes
no wrong LGTM

2021-09-09 18:04 UTC, theomega24 commented
If this is “no wrong” you would have checked and know that the domain for the repo isn’t in use anymore. So really there is much wrong lol

2021-09-09 18:23 UTC, Oharass commented
This is a big issue. There is no wrongs, but will not work.

2021-09-09 18:25 UTC, theomega24 commented
Well duh! It’s my code that I wrote, I think I would know. Also this hasn’t been tested so there could very well be “wrongs”

2021-09-09 18:26 UTC, Oharass commented
Sorry perhaps I'm not knowing correctly.

2021-09-10 08:27 UTC, CyberFlameGO commented
Interesting feature, I've not seen this implemented in a server before

2021-09-12 19:33 UTC, theomega24 commented
Just waiting for @BillyGalbreath

2021-09-16 19:47 UTC, BillyGalbreath commented on patches/server/0258-UPnP-Port-Forwarding.patch
> +Date: Sun, 11 Jul 2021 10:22:55 -0400
https://github.com/pl3xgaming/Purpur/blob/ver/1.15/patches/server/0088-UPnP-Port-Forwarding-Service.patch#L2-L3 ;)

2021-09-16 19:55 UTC, theomega24 commented on patches/server/0258-UPnP-Port-Forwarding.patch
> +Date: Sun, 11 Jul 2021 10:22:55 -0400
Must have missed that

2021-09-30 17:58 UTC, Encode42 approved these changes

2021-10-02 22:53 UTC, merged