Option for beds to explode on villager sleep
pl3xgaming/Purpur pull request #638
Opened 2021-08-31 14:52 UTC by 12emin34

This patch allows beds to explode when villagers try to sleep (only in nether and end, of course).

2021-08-31 14:59 UTC, theomega24 approved these changes

2021-09-01 20:48 UTC, granny commented on patches/server/0257-Option-for-beds-to-explode-on-villager-sleep.patch
> ++        bedExplodeOnVillagerSleep = getBoolean("blocks.bed.explode-on-villager-sleep", bedExplodeOnVillagerSleep);
could be separated into three options for overworld, end, and nether;
```yml
blocks:
  bed:
    explode-on-villager-sleep:
      overworld: false
      nether: false
      end: false
```

2021-09-01 20:50 UTC, Encode42 commented on patches/server/0257-Option-for-beds-to-explode-on-villager-sleep.patch
> ++        bedExplodeOnVillagerSleep = getBoolean("blocks.bed.explode-on-villager-sleep", bedExplodeOnVillagerSleep);
No need since the config option is per-world

2021-09-01 20:51 UTC, 12emin34 commented on patches/server/0257-Option-for-beds-to-explode-on-villager-sleep.patch
> ++        bedExplodeOnVillagerSleep = getBoolean("blocks.bed.explode-on-villager-sleep", bedExplodeOnVillagerSleep);
Good idea, will do when i have time tommorow

2021-09-01 20:51 UTC, 12emin34 commented on patches/server/0257-Option-for-beds-to-explode-on-villager-sleep.patch
> ++        bedExplodeOnVillagerSleep = getBoolean("blocks.bed.explode-on-villager-sleep", bedExplodeOnVillagerSleep);
Oh yeah i forgot it's per world

2021-09-01 20:57 UTC, Encode42 requested changes

2021-09-01 20:57 UTC, Encode42 commented on patches/server/0257-Option-for-beds-to-explode-on-villager-sleep.patch
> ++            if (blockState.getBlock() instanceof net.minecraft.world.level.block.BedBlock && (this.level.isNether() || this.level.isTheEnd())) {
Remove the nether and end check, this would make it properly per-world

2021-09-01 22:10 UTC, Encode42 approved these changes

2021-09-01 22:16 UTC, theomega24 approved these changes

2021-09-01 22:17 UTC, DoctaEnkoda approved these changes

2021-09-01 22:19 UTC, Encode42 commented on patches/server/0257-Option-for-beds-to-explode-on-villager-sleep.patch
> ++            BlockState blockState = this.level.getBlockState(pos);
Do we need to create an allocation here? IMO it'd be easier to just do: 
```java
if (level.purpurConfig.bedExplodeOnVillagerSleep && this.level.getBlockState(pos).getBlock() instanceof net.minecraft.world.level.block.BedBlock) {
...
```

2021-09-08 03:50 UTC, granny approved these changes

2021-09-09 02:14 UTC, Oharass approved these changes
LGTM!

2021-09-10 15:33 UTC, merged