permission for idle kick
pl3xgaming/Purpur pull request #657
Opened 2021-09-12 19:32 UTC by Oharass

https://github.com/pl3xgaming/Purpur/discussions/656

This adds

2021-09-12 19:44 UTC, granny requested changes
needs to be merged into `0013-AFK-API.patch`

2021-09-12 19:44 UTC, Oharass commented
ok.

2021-09-12 19:51 UTC, Oharass commented
done

2021-09-13 02:23 UTC, theomega24 approved these changes

2021-09-13 04:08 UTC, BillyGalbreath requested changes

2021-09-13 04:08 UTC, BillyGalbreath commented on patches/server/0013-AFK-API.patch
> ++            if (!this.player.level.purpurConfig.idleTimeoutKick || org.bukkit.Bukkit.getPlayer(this.player.getUUID()).hasPermission("purpur.bypassIdleKick")) {
we need to find a way to cache this permission check so it's not being performed every single tick

2021-09-13 11:36 UTC, Oharass commented on patches/server/0013-AFK-API.patch
> ++            if (!this.player.level.purpurConfig.idleTimeoutKick || org.bukkit.Bukkit.getPlayer(this.player.getUUID()).hasPermission("purpur.bypassIdleKick")) {
I will.

2021-09-13 12:59 UTC, YouHaveTrouble commented on patches/server/0013-AFK-API.patch
> ++            if (!this.player.level.purpurConfig.idleTimeoutKick || org.bukkit.Bukkit.getPlayer(this.player.getUUID()).hasPermission("purpur.bypassIdleKick")) {
why not just check that every 5-10 ticks?
Shouldn't make a big difference afaik

2021-09-13 13:09 UTC, DoctaEnkoda commented on patches/server/0013-AFK-API.patch
> ++            if (!this.player.level.purpurConfig.idleTimeoutKick || org.bukkit.Bukkit.getPlayer(this.player.getUUID()).hasPermission("purpur.bypassIdleKick")) {
And we can also use : `this.player.getBukkitEntity().hasPermission("purpur.bypassIdleKick")`

2021-09-13 14:45 UTC, Oharass commented on patches/server/0013-AFK-API.patch
> ++            if (!this.player.level.purpurConfig.idleTimeoutKick || org.bukkit.Bukkit.getPlayer(this.player.getUUID()).hasPermission("purpur.bypassIdleKick")) {
I had no idea such a method existed!!! Perhaps there should be javadoc published for this. It will make development much easier. I will evaluate the best way to reduce permission check when done working.

2021-09-13 22:48 UTC, Oharass commented on patches/server/0013-AFK-API.patch
> ++            if (!this.player.level.purpurConfig.idleTimeoutKick || org.bukkit.Bukkit.getPlayer(this.player.getUUID()).hasPermission("purpur.bypassIdleKick")) {
it caches. I add. Tell me discord Oharass#8311 on PurPur discord if I do wrong or here.

2021-09-16 20:41 UTC, merged