Add water damage to all endermobs and magmacubes
pl3xgaming/Purpur pull request #661
Opened 2021-09-14 22:59 UTC by ShadowPhrogg32642342

2021-09-16 19:40 UTC, BillyGalbreath requested changes

2021-09-16 19:40 UTC, BillyGalbreath commented on patches/server/0259-add-water-damage-to-all-endermobs-and-magmacube.patch
> ++    public boolean isSensitiveToWater() {
Move this whole method above `// Purpur end` since we're adding it to this class

2021-09-16 19:40 UTC, BillyGalbreath commented on patches/server/0259-add-water-damage-to-all-endermobs-and-magmacube.patch
> ++    public boolean isSensitiveToWater() {
Move this whole method above `// Purpur end` since we're adding it to this class

2021-09-16 19:40 UTC, BillyGalbreath commented on patches/server/0259-add-water-damage-to-all-endermobs-and-magmacube.patch
> ++    @Override
Move this whole method above `// Purpur end` since we're adding it to this class

2021-09-16 19:41 UTC, BillyGalbreath commented
I like it. Maybe we should extend this to all mobs?

2021-09-16 20:33 UTC, YouHaveTrouble commented
> I like it. Maybe we should extend this to all mobs?

Yes. 

Also, shouldn't it be in [this patch](https://github.com/pl3xgaming/Purpur/blob/ver/1.17.1/patches/server/0153-Toggle-for-water-sensitive-mob-damage.patch)?

2021-09-16 20:35 UTC, granny commented
> > I like it. Maybe we should extend this to all mobs?
> 
> Yes.
> 
> Also, shouldn't it be in [this patch](https://github.com/pl3xgaming/Purpur/blob/ver/1.17.1/patches/server/0153-Toggle-for-water-sensitive-mob-damage.patch)?

merging with the mentioned patch would be preferred

2021-09-16 20:48 UTC, ShadowPhrogg32642342 commented
Will change that patch then, I did notice the patch, but did not know about the etiquette of changing another's patch so better be safe, I submitted another.

2021-09-17 22:46 UTC, ShadowPhrogg32642342 commented
extended config options to all mobs
moved changes back to original patch
fixed formatting issues

2021-09-29 20:23 UTC, granny requested changes
the naming of some config options does not match

`mobs.caveSpider.takes-damage-from-water`
should be
`mobs.cave_spider.takes-damage-from-water`
etc.

also requires a rebase

2021-10-08 12:56 UTC, closed without merging