Addition potion functionality
pl3xgaming/Purpur pull request #670
Opened 2021-09-17 11:24 UTC by DaRacci

Adding an addition object that allows plugin devs to add data to potions allows them to add for example a boolean or a simple string that they can then use to identify if the potion was applied from their plugin.

2021-09-17 16:32 UTC, DoctaEnkoda commented on patches/api/0051-The-purpose-of-this-patch-it-to-add-additional-funct.patch
> ++                .put(ICON, icon)
Restore indentation

2021-09-18 14:53 UTC, DoctaEnkoda requested changes

2021-09-18 14:53 UTC, DoctaEnkoda commented on patches/api/0051-The-purpose-of-this-patch-it-to-add-additional-funct.patch
> ++    @Contract("-> null")
Restore

2021-09-19 13:47 UTC, DoctaEnkoda requested changes

2021-09-19 13:47 UTC, DoctaEnkoda commented on patches/api/0051-The-purpose-of-this-patch-it-to-add-additional-funct.patch
> ++                .put(ICON, icon)
Restore pls

2021-09-19 13:47 UTC, DoctaEnkoda commented on patches/api/0051-The-purpose-of-this-patch-it-to-add-additional-funct.patch
> ++    @Contract("-> null")
Restore pls

2021-09-19 14:32 UTC, DaRacci commented on patches/api/0051-The-purpose-of-this-patch-it-to-add-additional-funct.patch
> ++    @Contract("-> null")
my bad sorry, first time committing something

2021-09-19 15:35 UTC, DoctaEnkoda commented
Rebuild your patch

2021-09-20 03:47 UTC, DaRacci commented
> 
> 
> Rebuild your patch

I think i got it right this time, is it all good now?

2021-09-21 16:54 UTC, DoctaEnkoda requested changes

2021-09-21 16:54 UTC, DoctaEnkoda commented on patches/api/0051-The-purpose-of-this-patch-it-to-add-additional-funct.patch
> ++        this(getEffectType(map), getInt(map, DURATION), getInt(map, AMPLIFIER), getBool(map, AMBIENT, false), getBool(map, PARTICLES, true), getBool(map, ICON, getBool(map, PARTICLES, true)), getObj
add `// Purpur`

2021-09-21 16:54 UTC, DoctaEnkoda commented on patches/api/0051-The-purpose-of-this-patch-it-to-add-additional-funct.patch
> ++        return this.type.equals(that.type) && this.ambient == that.ambient && this.amplifier == that.amplifier && this.duration == that.duration && this.particles == that.particles && this.icon == t
Add `// Purpur`

2021-09-30 17:58 UTC, Encode42 approved these changes

2021-10-17 10:06 UTC, closed without merging

2021-10-17 10:06 UTC, DaRacci commented
Outdated, check https://github.com/pl3xgaming/Purpur/pull/710 for the updated PR