fix empty message for cannot-ride-mob
pl3xgaming/Purpur pull request #685
Opened 2021-09-26 01:29 UTC by Oharass

Fix #684. Use empty message for cannot-ride-mob. This adds

2021-09-26 01:47 UTC, theomega24 approved these changes

2021-09-26 02:38 UTC, BillyGalbreath requested changes
While this would fix it for this specific option, it won't for any of the others. A better way is to check in the `sendMessage` method. Seems like when I switched everything to components that logic was lost somewhere.

2021-09-26 02:43 UTC, Oharass commented
ok. I will fix this.

2021-09-26 02:51 UTC, Oharass commented
I think this is correct now. Fixed for all. I use "isEmpty" instead of "isBlank" so you can still send blank message if you like with " ". This adds.

2021-09-30 17:52 UTC, Encode42 commented on patches/server/0006-Component-related-conveniences.patch
> ++        if (org.apache.commons.lang3.StringUtils.isNotEmpty(message)) {
Why use StringUtils instead of Java's native `String#isBlank`?

2021-09-30 17:54 UTC, Oharass commented on patches/server/0006-Component-related-conveniences.patch
> ++        if (org.apache.commons.lang3.StringUtils.isNotEmpty(message)) {
It handles null. I may also do `message != null && !message.isEmpty()`

2021-09-30 18:02 UTC, Encode42 commented on patches/server/0006-Component-related-conveniences.patch
> ++        if (org.apache.commons.lang3.StringUtils.isNotEmpty(message)) {
Ah, I see. Was just wondering

2021-09-30 18:02 UTC, Encode42 requested changes
LGTM, just resolve conflicts

2021-10-02 02:01 UTC, closed without merging