Potion NamespacedKey
pl3xgaming/Purpur pull request #710
Opened 2021-10-17 10:05 UTC by DaRacci

Unlike the previous api change i had made a PR for this time it _actually works_ and is now utilizing the namespacedkey system.

2021-10-17 10:25 UTC, Euphillya requested changes

2021-10-17 10:25 UTC, Euphillya commented on patches/server/0262-Potion-NamespacedKey.patch
> ++        this(type, duration, amplifier, ambient, showParticles, showIcon, null);
unnecessary diff

2021-10-17 10:25 UTC, Euphillya commented on patches/server/0262-Potion-NamespacedKey.patch
> ++        NamespacedKey key = NamespacedKey.fromString(nbt.getString("Key"));
add Purpur comment

2021-10-17 10:25 UTC, Euphillya commented on patches/server/0262-Potion-NamespacedKey.patch
> ++        return new MobEffectInstance(type, j, i < 0 ? 0 : i, bl, bl2, bl3, key, mobEffectInstance);
Add Purpur comment

2021-10-17 10:25 UTC, Euphillya commented on patches/server/0262-Potion-NamespacedKey.patch
> ++        return new PotionEffect(type, duration, amp, ambient, particles, key);
No need to create a variable, just return directly :
` return new PotionEffect(type, duration, amp, ambient, particles, effect.getKey()); // Purpur`

2021-10-17 10:25 UTC, Euphillya commented on patches/server/0262-Potion-NamespacedKey.patch
> ++import org.bukkit.NamespacedKey;
unnecessary diff

2021-10-17 10:25 UTC, Euphillya commented on patches/server/0262-Potion-NamespacedKey.patch
> ++    private NamespacedKey key;
Add Purpur comment

2021-10-17 10:25 UTC, Euphillya commented on patches/api/0050-Potion-NamespacedKey.patch
> ++    private static NamespacedKey getKey(@NotNull Map<?, ?> map) {
Add Purpur comment

2021-10-17 10:25 UTC, Euphillya commented on patches/api/0050-Potion-NamespacedKey.patch
> ++        this(type, duration, amplifier, ambient, particles, icon, null);
Add Purpur End comment

2021-10-17 10:25 UTC, Euphillya commented on patches/api/0050-Potion-NamespacedKey.patch
> ++    private static final String KEY = "namespacedkey";
Add Purpur Comment

2021-10-17 10:26 UTC, Euphillya requested changes

2021-10-17 10:26 UTC, Euphillya commented on patches/api/0050-Potion-NamespacedKey.patch
> ++    public PotionEffect(@NotNull PotionEffectType type, int duration, int amplifier, boolean ambient, boolean particles, boolean icon, NamespacedKey key) {
Add Purpur Comment

2021-10-17 10:30 UTC, DaRacci commented on patches/server/0262-Potion-NamespacedKey.patch
> ++        this(type, duration, amplifier, ambient, showParticles, showIcon, null);
woops didn't mean to include that

2021-10-17 10:31 UTC, DaRacci commented on patches/server/0262-Potion-NamespacedKey.patch
> ++        this(type, duration, amplifier, ambient, showParticles, showIcon, null);
wait no actually thats needed because i changed the order somewhat hrrr

2021-10-17 10:31 UTC, DaRacci commented on patches/server/0262-Potion-NamespacedKey.patch
> ++        this(type, duration, amplifier, ambient, showParticles, showIcon, null);
would it be better to implement a new constructor to match the old order or leave it?

2021-10-17 10:40 UTC, Euphillya commented on patches/server/0262-Potion-NamespacedKey.patch
> ++        this(type, duration, amplifier, ambient, showParticles, showIcon, null);
I think new constructor is better to maintien API

2021-10-17 11:51 UTC, Euphillya requested changes

2021-10-17 11:51 UTC, Euphillya commented on patches/server/0262-Potion-NamespacedKey.patch
> ++        return new PotionEffect(type, duration, amp, ambient, particles, effect.getKey());
Add Purpur comment

2021-11-11 12:04 UTC, Encode42 reviewed
LGTM, needs a rebase though

2021-11-19 10:54 UTC, DaRacci commented
Sorry for closing and opening again, check https://github.com/pl3xgaming/Purpur/pull/754 for the updated PR

2021-11-19 10:54 UTC, closed without merging