Add option to disable zombie villagers cure
pl3xgaming/Purpur pull request #711
Opened 2021-10-18 12:33 UTC by rafaelflromao

2021-10-18 12:37 UTC, Euphillya requested changes

2021-10-18 12:37 UTC, Euphillya commented on patches/server/0262-Add-option-to-disable-zombie-villagers-cure.patch
> ++        if (itemstack.is(Items.GOLDEN_APPLE) && level.purpurConfig.zombieVillagerCureEnabled) {
Add purpur comment

2021-10-18 12:37 UTC, Euphillya commented on patches/server/0262-Add-option-to-disable-zombie-villagers-cure.patch
> ++
unnecessary diff

2021-10-18 14:49 UTC, BillyGalbreath requested changes

2021-10-18 14:49 UTC, BillyGalbreath commented on patches/server/0262-Add-option-to-disable-zombie-villagers-cure.patch
> ++        if (itemstack.is(Items.GOLDEN_APPLE) && level.purpurConfig.zombieVillagerCureEnabled) { // Purpur
move this check down one line to the weakness check, that way if it fails it will go to the consume

2021-10-18 15:22 UTC, rafaelflromao commented on patches/server/0262-Add-option-to-disable-zombie-villagers-cure.patch
> ++        if (itemstack.is(Items.GOLDEN_APPLE) && level.purpurConfig.zombieVillagerCureEnabled) { // Purpur
If it is disabled I think that is suppose to pass, isn't it?

2021-10-18 15:43 UTC, BillyGalbreath commented on patches/server/0262-Add-option-to-disable-zombie-villagers-cure.patch
> ++        if (itemstack.is(Items.GOLDEN_APPLE) && level.purpurConfig.zombieVillagerCureEnabled) { // Purpur
That's what I originally thought, too. But I created a nasty bug by passing everything in instead of consuming the things that need to be consumed in the ridables patch https://github.com/pl3xgaming/Purpur/issues/611 (eventually, i'll get around to fixing that)

2021-10-19 12:17 UTC, rafaelflromao commented on patches/server/0262-Add-option-to-disable-zombie-villagers-cure.patch
> ++        if (itemstack.is(Items.GOLDEN_APPLE) && level.purpurConfig.zombieVillagerCureEnabled) { // Purpur
Resolved

2021-10-19 12:30 UTC, katekerllenevich approved these changes

2021-10-19 12:31 UTC, Euphillya approved these changes

2021-10-19 14:52 UTC, BillyGalbreath approved these changes

2021-10-25 19:01 UTC, merged