Potion NamespacedKey. again...
pl3xgaming/Purpur pull request #754
Opened 2021-11-19 10:54 UTC by DaRacci

Continued from https://github.com/pl3xgaming/Purpur/pull/710
Sorry for closing and reopening a new pr again, i was having issue with my previous fork and I'm not too experienced with pr and fork stuff so i deleted it and forked again to make the changes needed.

I've had these changes in use on a production server for about a month or so with no more issues so it should be all good with plugins and what not.

- I've fixed an issue that caused  serialized potion effects to cause null issues etc
- Now custom potion effects on CraftMetaPotion have the namespacedKeys too
- No longer serialize null namespaces for potions
- Added some annotations
- Probably other misc stuff too

2021-11-19 12:55 UTC, DoctaEnkoda requested changes

2021-11-19 12:55 UTC, DoctaEnkoda commented on patches/api/0045-Potion-NamespacedKey.patch
> ++    @Contract("-> null")
Restore indentation

2021-11-19 12:55 UTC, DoctaEnkoda commented on patches/api/0045-Potion-NamespacedKey.patch
> ++        return new PotionEffect(type, duration, amplifier, ambient, particles, icon, key);
Add Purpur comment

2021-11-19 12:55 UTC, DoctaEnkoda commented on patches/api/0045-Potion-NamespacedKey.patch
> ++        return new PotionEffect(this.type, duration, amplifier, ambient, particles, icon, key);
Add Purpur comment

2021-11-19 12:55 UTC, DoctaEnkoda commented on patches/api/0045-Potion-NamespacedKey.patch
> ++        return new PotionEffect(this.type, duration, amplifier, ambient, particles, icon, key);
Add Purpur comment

2021-11-19 12:55 UTC, DoctaEnkoda commented on patches/api/0045-Potion-NamespacedKey.patch
> ++        return new PotionEffect(this.type, duration, amplifier, ambient, particles, icon, key);
Add Purpur comment

2021-11-19 12:55 UTC, DoctaEnkoda commented on patches/api/0045-Potion-NamespacedKey.patch
> ++        return new PotionEffect(this.type, duration, amplifier, ambient, particles, icon, key);
Add Purpur comment

2021-11-19 12:55 UTC, DoctaEnkoda commented on patches/api/0045-Potion-NamespacedKey.patch
> ++        return new PotionEffect(this.type, duration, amplifier, ambient, particles, icon, key);
Add Purpur Start comment

2021-11-19 12:55 UTC, DoctaEnkoda commented on patches/api/0045-Potion-NamespacedKey.patch
> ++    // Paper start // Purpur start - add key
dont need comment here

2021-11-19 12:55 UTC, DoctaEnkoda commented on patches/api/0045-Potion-NamespacedKey.patch
> ++    // Purpur start - Key instead of icon constructor and keyless normal.
Move Purpur Start

2021-11-19 12:55 UTC, DoctaEnkoda commented on patches/api/0045-Potion-NamespacedKey.patch
> ++    private final NamespacedKey key; // Purpur
On one line

2021-11-19 12:55 UTC, DoctaEnkoda commented on patches/server/0257-Potion-NamespacedKey.patch
> +
Add Purpur Start Comment

2021-11-19 12:55 UTC, DoctaEnkoda commented on patches/server/0257-Potion-NamespacedKey.patch
> ++
Add Purpur End Comment

2021-11-29 03:34 UTC, DaRacci commented
Should I reapply this to the 1.18 branch and make a pull request from there as it seems the 1.17.1 branch has had its final updates

2021-11-29 13:25 UTC, Encode42 commented
Once our 1.18 release is ready, yes. We're currently in a feature freeze as the update takes place

2021-12-12 17:55 UTC, Encode42 commented
Superseded by #783

2021-12-12 17:55 UTC, closed without merging