Add Potion NamespacedKey Patches
pl3xgaming/Purpur pull request #783
Opened 2021-12-12 06:12 UTC by DaRacci

New PR into 1.18.1, no changes since last PR

2021-12-12 15:29 UTC, Encode42 approved these changes

2021-12-12 16:47 UTC, Camotoy commented
I don't understand the purpose of this PR. Doesn't the persistent data container exist for this reason? Is there something here that existing functionality doesn't provide? Besides that, have you tested if this data stays should the user switch from Purpur to another downstream server build? Also, why specifically for potions? In my opinion, this seems like a really, really niche feature.

2021-12-12 17:01 UTC, Camotoy commented
My apologies; this is for actual effects, not any sort of entity. Though the point about the data persisting between server forks *should* still persist.

2021-12-13 09:04 UTC, DaRacci commented
> My apologies; this is for actual effects, not any sort of entity. Though the point about the data persisting between server forks _should_ still persist.

I haven't done any form of testing between forks however due to modifying the serializer the data wont persist through forks as it won't load the key and would override it once saved again

2021-12-15 21:13 UTC, Encode42 requested changes

2021-12-15 21:13 UTC, Encode42 commented on patches/api/0043-Potion-NamespacedKey.patch
> ++    @Contract("-> null")
Unmodify these lines so we don't run into upstream conflicts

2021-12-15 21:15 UTC, Encode42 commented
> Though the point about the data persisting between server forks should still persist.
Due to the nature of NBT's implementation, all unused data will be wiped. This applies to Paper and all other Purpur patches that modify NBT data. The general census is that when you switch forks, you'll lose all of the fork's features.

Because of this, I believe it's fine if the data does not persist between forks.

2021-12-16 04:21 UTC, DaRacci commented on patches/api/0043-Potion-NamespacedKey.patch
> ++    @Contract("-> null")
I cannot count how many times ive fixed this now, For some reason intellij keeps formatting them and i dont notice until i get told about it like this

2021-12-26 21:21 UTC, BillyGalbreath approved these changes

2021-12-26 21:39 UTC, merged