Add Fire ImmunityAPI
pl3xgaming/Purpur pull request #891
Opened 2022-02-04 09:05 UTC by DaRacci

2022-02-12 13:03 UTC, BillyGalbreath requested changes

2022-02-12 13:03 UTC, BillyGalbreath commented on patches/api/0048-Fire-Immunity-API.patch
> +-
I'll go over the rest of this PR when I have more time, but just wanted to point out that this breaks [ABI](https://stackoverflow.com/questions/2171177/what-is-an-application-binary-interface-abi). We'll have to keep these methods here for compatibility, and in the implementation just send them to `super`

2022-02-12 13:16 UTC, DaRacci commented on patches/api/0048-Fire-Immunity-API.patch
> +-
Thank for pointing to that info on ABI as i didn't know about that, and on the point of this since in Item i needs to override both the nullable boolean and primitive would the best way of doing this be to be adding in this due to needing to call this on the item which is what the other override calls
```java
@Override
public void setImmuneToFire(boolean immuneToFire) {
    this.setImmuneToFire((Boolean) immuneToFire);
}
```

2022-02-12 13:36 UTC, BillyGalbreath commented on patches/api/0048-Fire-Immunity-API.patch
> +-
that'll work, too, since the method signatures are different. i prefer the super way, because it's more clear what it's doing and doesnt need an explicit cast. ;)
```java
    @Override
    public void setImmuneToFire(boolean immuneToFire) {
        super.setImmuneToFire(immuneToFire);
    }
    ```

2022-02-12 13:42 UTC, DaRacci commented on patches/api/0048-Fire-Immunity-API.patch
> +-
When i was doing my initial testing using super in the CraftItem didn't work since the entity which needs to be effects is the item field from what i saw if i didn't somehow mess it up, and I'll add a deprecated annotation onto the old method too

2022-05-09 21:26 UTC, theomega24 requested changes

2022-05-09 21:26 UTC, theomega24 commented on patches/server/0269-Fire-Immunity-API.patch
> +-import net.minecraft.world.level.block.state.BlockBehaviour;
don't mess with this

2022-05-09 21:26 UTC, theomega24 commented on patches/server/0269-Fire-Immunity-API.patch
> ++import org.jetbrains.annotations.*;
use fqdn

2022-05-09 21:26 UTC, theomega24 commented on patches/server/0269-Fire-Immunity-API.patch
> ++    public void setImmuneToFire(@Nullable Boolean immuneToFire) {
`boolean` not `Boolean`

2022-05-09 21:26 UTC, theomega24 commented on patches/server/0269-Fire-Immunity-API.patch
> ++    public @Nullable Boolean immuneToFire = null; // Purpur - Fire immune API
`boolean` not `Boolean`

2022-05-09 21:26 UTC, theomega24 commented on patches/api/0048-Fire-Immunity-API.patch
> ++    void setImmuneToFire(@Nullable Boolean fireImmune);
`boolean` not `Boolean`

2022-05-09 21:26 UTC, theomega24 commented on patches/api/0048-Fire-Immunity-API.patch
> ++    @Deprecated
i'm not sure this is necessary

2022-05-24 13:26 UTC, DaRacci commented on patches/server/0269-Fire-Immunity-API.patch
> ++    public void setImmuneToFire(@Nullable Boolean immuneToFire) {
the idea of having it be Boolean is so it can be set to null and restore default behaviour which i think is a better way than using another method or something to signal that its disabled

2022-05-24 20:38 UTC, theomega24 commented on patches/server/0269-Fire-Immunity-API.patch
> ++    public void setImmuneToFire(@Nullable Boolean immuneToFire) {
Maybe take a look at how I did this?
https://github.com/PurpurMC/Purpur/blob/ver/1.18.2/patches/api/0035-API-for-any-mob-to-burn-daylight.patch

2022-05-25 03:48 UTC, DaRacci commented on patches/server/0269-Fire-Immunity-API.patch
> ++    public void setImmuneToFire(@Nullable Boolean immuneToFire) {
I think its better to be able to do it this way because if you want to set the behaviour to the default for the mob you'd have to know the mob and its default setting, however with this method and how I've been using it in my development has been used with a system that doesn't track a certain mob and doesn't know the default so being able to null it and have it just work makes it so much easier to use and work with.

2022-05-25 03:56 UTC, DaRacci commented on patches/server/0269-Fire-Immunity-API.patch
> ++    public void setImmuneToFire(@Nullable Boolean immuneToFire) {
unless im missing something the only way to get the default fire immune setting is like this
```kotlin
val default = (entity as CraftEntity).handle.type.fireImmune()
entity.setImmuneToFire(default)
```
but with being able to null it
```kotlin
entity.setImmuneToFire(null)
```

2022-05-25 03:59 UTC, DaRacci commented on patches/api/0048-Fire-Immunity-API.patch
> ++    @Deprecated
While it may not be necessary i think deprecating this and pointing towards the universal fire immune method is a better idea

2022-05-25 17:16 UTC, 4drian3d commented on patches/server/0269-Fire-Immunity-API.patch
> ++    public void setImmuneToFire(@Nullable Boolean immuneToFire) {
Then it may be better to use a [TriState](https://jd.adventure.kyori.net/api/4.10.1/net/kyori/adventure/util/TriState.html) instead of a Boolean which may be null. This way you can avoid using booleans as objects and avoid having a null variable

2022-05-25 20:01 UTC, theomega24 commented on patches/server/0269-Fire-Immunity-API.patch
> ++    public void setImmuneToFire(@Nullable Boolean immuneToFire) {
I still think thats unnecessary and that a simple `boolean` (matching with the burn in daylight API) is fine.

2022-10-25 10:58 UTC, granny approved these changes

2022-10-25 10:59 UTC, merged