Configurable map update interval
pl3xgaming/Purpur pull request #940
Opened 2022-03-24 11:55 UTC by minhh2792

Mojang decided to increase the update interval of map to 5 ticks, in some server which utilize it this is kinda slow

This PR made the value configurable so the server admin can adjust as their liking

I tested this and having no issue, however I can't record a comparison video of it because of my potato pc :'(

2022-03-24 11:58 UTC, theomega24 requested changes

2022-03-24 11:58 UTC, theomega24 commented on patches/server/0272-Configurable-map-update-interval.patch
> ++        version = getInt("config-version", 28);
dont change this

2022-03-24 12:05 UTC, BillyGalbreath requested changes

2022-03-24 12:05 UTC, BillyGalbreath commented on patches/server/0272-Configurable-map-update-interval.patch
> ++    }
this could be per-world if you use the player's world

2022-03-24 12:05 UTC, minhh2792 commented on patches/server/0272-Configurable-map-update-interval.patch
> ++        version = getInt("config-version", 28);
Reverted

2022-03-24 12:07 UTC, minhh2792 commented on patches/server/0272-Configurable-map-update-interval.patch
> ++    }
I think it is better to leave it in global config, I don't think anyone would want long update interval anyway :p

2022-03-24 12:09 UTC, BillyGalbreath commented on patches/server/0272-Configurable-map-update-interval.patch
> ++    }
you'd be surprised. one thing i've learned with purpur over the years is no one wants anything until they realize its possible. its a simple edit to make it per-world compatible, so might as well do that before people get used to it being global and we have to make a migration for it ;)

2022-03-24 12:12 UTC, minhh2792 commented on patches/server/0272-Configurable-map-update-interval.patch
> ++    }
yeah, i will work on it :)

2022-03-26 10:03 UTC, minhh2792 commented
Moved to per world config, everything has been tested. This PR is now ready to merge

2022-03-26 12:11 UTC, BillyGalbreath approved these changes

2022-03-26 12:12 UTC, theomega24 approved these changes

2022-03-28 00:19 UTC, kev626 commented
This patch makes no sense and should not be included.

First, you can see in this patch, if the map contains dirty data, then it will always be immediately rendered with no delay. Configuring the update interval will have no noticeable impact on performance nor will it have any noticeable impact on player appearance to the game due to this dirty check.

Second, there's no way your players are noticing quarter-second delay in maps, even if it were happening.

2022-03-28 01:03 UTC, minhh2792 commented
This patch not meant to be "performance improvement" anyway

A Minecraft CS:GO server that utilizes the Map, and 5 ticks delay per update is really slow and noticeable  (https://youtu.be/-q3i_YnE3l8)

2022-03-28 01:19 UTC, kev626 commented
> This patch is not meant to be "performance improvement" anyway
> 
> A Minecraft CS:GO server that utilizes the Map, and 5 ticks delay per update is really slow and noticeable
> 
> Edit link: https://youtu.be/i_0NrTb2Rsc

Then do you explain the presence of the “dirty” check?

2022-03-28 01:21 UTC, minhh2792 commented
What dirty check

2022-03-28 01:22 UTC, minhh2792 commented
This patch has nothing to do with the check tho, it just make the interval configurable

2022-03-28 01:22 UTC, kev626 commented
> What dirty check

`if (!this.dirtyData && …)`
Did you even read the patch you were modifying?

2022-03-28 01:23 UTC, minhh2792 commented
> This patch has nothing to do with the check tho, it just make the interval configurable

2022-03-28 01:26 UTC, kev626 commented
> This patch has nothing to do with the check tho, it just make the interval configurable

This is why I think you didn’t even read the patch you’re attempting to modify. If the data used to render the map is changed, the map already updates immediately. In this sense, the interval doesn’t even matter.

The interval only serves to update the map data if for some reason the data is changed without the dirty flag being set (which should be never). Having the interval configurable at all is totally useless, as it’s value does not have any impact whatsoever on gameplay.

2022-03-28 01:32 UTC, minhh2792 commented
I appreciate the clarification, in my case, the map (you can watch the video) is slow. Changing the value works for me so I make this PR, maybe other servers also having this problem as well

If this PR is closed then I will just port it to my fork :fork:

2022-03-30 09:32 UTC, amadeusmz commented
@kev626 It will not be immediately rendered, it will check for dirty every 5 ticks as I told you on Pufferfish's Discord.
This patch worked for me and I really need it.

2022-03-30 10:20 UTC, kev626 commented
> @kev626 It will not be immediately rendered, it will check for dirty every 5 ticks as I told you on Pufferfish Discord.
> 
> This patch worked for me and I really need it.

If you need a map to be immediately rendered to a player, you can do this via the API by calling Player#sendMap(MapView). There is no need for any patch.

Regardless, it's not my project and purpur is free to add whatever they like, but this is truly not necessary.

2022-03-30 16:56 UTC, famous1622 commented
This patch actually fixes a mismatch between API behavior in Spigot and Paper. Perhaps this would be better brought up upstream?

2022-04-14 00:42 UTC, closed without merging