Config to prevent horses from standing when hurt
pl3xgaming/Purpur pull request #957
Opened 2022-04-14 18:18 UTC by galacticwarrior9

This PR adds a config option to toggle horses standing on their hind legs when taking damage.

This behaviour can be undesirable to servers who wish to improve mounted combat. There is currently no way to prevent this behaviour through the API.

2022-04-14 20:53 UTC, Encode42 requested changes

2022-04-14 20:53 UTC, Encode42 commented on patches/server/0272-Config-to-prevent-horses-from-standing-when-hurt.patch
> ++        if (this.random.nextInt(3) == 0 && this.level.purpurConfig.horseStandWhenHurt) { // Purpur
Add the config check before the random check, we don't want to run unnecessary logic

2022-04-14 21:09 UTC, galacticwarrior9 commented on patches/server/0272-Config-to-prevent-horses-from-standing-when-hurt.patch
> ++        if (this.random.nextInt(3) == 0 && this.level.purpurConfig.horseStandWhenHurt) { // Purpur
Change made

2022-04-29 21:33 UTC, Encode42 approved these changes
LGTM, just needs additional testing and a potential rebase

2022-05-09 21:26 UTC, theomega24 approved these changes
lgtm

2022-05-09 21:48 UTC, merged